---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---
# **Reproducible Research: Course Project 1**  
###It is now possible to collect a large amount of data about personal movement using activity monitoring devices such as a Fitbit, Nike Fuelband, or Jawbone Up. These type of devices are part of the “quantified self” movement – a group of enthusiasts who take measurements about themselves regularly to improve their health, to find patterns in their behavior, or because they are tech geeks. But these data remain under-utilized both because the raw data are hard to obtain and there is a lack of statistical methods and software for processing and interpreting the data.

## **Loading and preprocessing the data**
#### Loading and unzipping the data. Looking at the summary of the data set. 
```{r echo=TRUE} 
unzip("./activity.zip")
activityData <- read.csv("./activity.csv")
summary(activityData)
```

## **What is mean total number of steps taken per day?**



## **What is the average daily activity pattern?**



## **Imputing missing values**



## **Are there differences in activity patterns between weekdays and weekends?**
